export default {
  SET_VK_USER_ID: 'SET_VK_USER_ID',
  SET_VK_USER_DATA: 'SET_VK_USER_DATA',
  GET_DEFAULT_CHAT_LIST: 'GET_DEFAULT_CHAT_LIST',
  GET_CURRRENT_CHAT_MSG: 'GET_CURRRENT_CHAT_MSG',
  SET_CURRRENT_CHAT_MSG_DATA: 'SET_CURRRENT_CHAT_MSG_DATA'
}